# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghist < Formula
  desc "Task management that lives in your repo."
  homepage "https://github.com/unnecessary-special-projects/ghist"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.0/ghist_darwin_amd64.tar.gz"
      sha256 "6c1277bcd5038b23de30181701b4c9f7089643d4e53997166c62e6e936d02f69"

      define_method(:install) do
        bin.install "ghist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.0/ghist_darwin_arm64.tar.gz"
      sha256 "4f2f5c673d90e6605a399828f2fb586023bd1f8fbcdf5f755f4d8080893cbce7"

      define_method(:install) do
        bin.install "ghist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.0/ghist_linux_amd64.tar.gz"
      sha256 "a7f2b0980a62a77255f5eda0ad2602afb1162382b6a0dce29271f4c04ef4573b"
      define_method(:install) do
        bin.install "ghist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.0/ghist_linux_arm64.tar.gz"
      sha256 "7375b796c8a10aa004efea1bda0514e339d52baf876c0477c7880832915b2b46"
      define_method(:install) do
        bin.install "ghist"
      end
    end
  end

  test do
    system "#{bin}/ghist", "--version"
  end
end
