# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghist < Formula
  desc "Task management that lives in your repo."
  homepage "https://github.com/unnecessary-special-projects/ghist"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.1/ghist_darwin_amd64.tar.gz"
      sha256 "a661327f9afebd05539ce74aba1cb447682e6d25c4916af718b4a4d82413454a"

      define_method(:install) do
        bin.install "ghist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.1/ghist_darwin_arm64.tar.gz"
      sha256 "384d4234990349688900df905039f230fb9ad1e26e49214c5efb60df6071e1d3"

      define_method(:install) do
        bin.install "ghist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.1/ghist_linux_amd64.tar.gz"
      sha256 "c0d1f7a82971c159ec5f1b183863dd8100e0b688df561321691cee0606e5d88a"
      define_method(:install) do
        bin.install "ghist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnecessary-special-projects/ghist/releases/download/v0.1.1/ghist_linux_arm64.tar.gz"
      sha256 "a3ddb1f7903ec3daa96238df4e19946c2a27e70855a9fdc7e8dcbcbc53a709c6"
      define_method(:install) do
        bin.install "ghist"
      end
    end
  end

  test do
    system "#{bin}/ghist", "--version"
  end
end
